### ISSUE TITLE
Using component from sharedModule in ionic app not working

### ISSUE THREAD

**Issue by edento** [benorama/ngrx-demo-workspace#1]
I have cloned your project and it was running perfectly. But, try to do the following change:
At `my-component` folder and added a style file `my-component.component.scss`. At `my-component.component.ts` I have referenced it:
```
@Component({
    selector: 'app-my-component',
    templateUrl: './my-component.component.html',
    styleUrls: ['./my-component.component.scss'] /// this line
})
```
When running the web app, everything works as expected, but when i use the same component at the ionic application, this error occures:
```
polyfills.js:3 Unhandled Promise rejection: Failed to load my-component.component.scss ; Zone: <root> ; Task: Promise.then ; Value: Failed to load my-component.component.scss 
```

I couldn't find a fix for that issue, can you please let me know it happens for you as well? this is the only thing I am missing..thank you!

**Comment by benorama** [comment]
Indeed, I also encountered this issue... That's why I removed the .scss file :).
I've not digged further since our goal is to mainly share NGRX stuff, but if anyone find a solution for that, let us know.
Maybe some custom stuff to do on the webpack side for SCSS on Ionic.

**Comment by edento** [comment]
Do you know if that problem exists in you [older architecture](https://github.com/benorama/ngrx-demo-apps)? 

thanks

**Comment by benorama** [comment]
@edento I think so.

**Comment by edento** [comment]
:(

Thank you

**Comment by edento** [comment]
I fixed that issue, if you're interested I have submitted a pull request.
