### ISSUE TITLE
Can't build with ionic cordova build ios --prod

### ISSUE THREAD

**Issue by benorama** [benorama/ngrx-demo-workspace#2]
Running `ionic cordova build ios --prod` does not work.
It generates a typescript compilation issue.

```
[15:12:41]  ngc started ... 
[15:12:45]  typescript error 
            Error during template compile of 'StoreModule' Function expressions are not supported in decorators in 
            'NgModule' 'NgModule' contains the error at @angular/core/core.ts(194,31) Consider changing the function 
            expression into an exported function. 
```

However it works fine without `--prod` or when running `ionic cordova emulate ios`

**Comment by benorama** [comment]
It would be interesting to create a brand new Ionic app and simply use Ngrx (without NX Workspace), in order to know if it's related to Nx Workspace or only to Ngrx Store.

**Comment by eladcandroid** [comment]
Try to upgrade @angular/cli for libs & apps and install @angular-devkit/core (needed for new versions of cli)

**Comment by benorama** [comment]
This issue seems to be solved with the latest libs (Ionic 4, Angular 6).
