### ISSUE TITLE
Can't build with ionic cordova build ios

### ISSUE THREAD

**Issue by benorama** [benorama/ngrx-demo-workspace#5]
I'm trying to build on iOS with latest Ionic4 (and Angular6).

Under the hood it runs `ng run mobile:ionic-cordova-build --platform=ios`
But the process exit with an `ENOENT: no such file or directory` error.

It looks like it is looking for `ngrx-demo-workspace/platforms/ios/platform_www/cordova.js`.
Path is incorrect, it should be `ngrx-demo-workspace/apps/mobile/platforms/ios/platform_www/cordova.js`

I've not find yet how to configure this.

**Comment by jhonscript** [comment]
it seems that several things changed after xplat arrived
https://nstudio.io/xplat/#6addionicapp

**Comment by benorama** [comment]
I've been able to solve this issue by installing the latest Ionic CLI (`4.3.0+`), which supports multi-app projects (see https://beta.ionicframework.com/docs/cli/configuration/#multi-app)
