### ISSUE TITLE
Seperate package.jsons

### ISSUE THREAD

**Issue by mitschmidt** [benorama/ngrx-demo-workspace#7]
Thanks @benorama for this great suggestion on how to integrate an Ionic project into an Nx workspace.

My team and I plan to use some parts of `ionic` in our web application as well, e.g. leverage existing UI components and share components that depend on `ionic` between web and mobile app projects. The problem: `ionic` is only installed in the nested package of the mobile project - we would have to redundantly install it in the root `package.json` with risk of diverging versions between these two.

Have you done such thing before and have any advise? Is it possible to spare the second nested `package.json`?

Thanks in advance
Tim

**Comment by voznik** [comment]
hi @mitschmidt 
please take a look at my forked [repo](https://github.com/voznik/nx-workspace), where I use a little bit different approach.
I wanted to update all dependencies, but then I went to creating new nx-workspace & new ionic app from cli. I use 1 package.json, so no need to `cd mobile`, just use `ng serve/build` from root folder.
also, I presented `ui` library to show how one can reuse some ui styles and functionality like modals in both apps.
